spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 9411

eureka:
  client:
    servcieUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false