spring:
  application:
    name: hello-spring-cloud-admin-ribbon
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8764

eureka:
  instance:
    hostname: localhost
  client:
    servcieUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/