spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/q513021617/spring-cloud-config.git
          search-paths: respo
          username: 1871901600@qq.com
          password: 3256028La.
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8888

eureka:
  client:
    servcieUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/