spring:
  application:
    name: hello-spring-cloud-service-admin
  zipkin:
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 8763

eureka:
  client:
    servcieUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/