spring:
  application:
    name: hello-spring-cloud-admin-ribbon

server:
  port: 8764

eureka:
  instance:
    hostname: localhost
  client:
    servcieUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/